-- =================================================================           
-- MÓDULO DE AUDITORIA E SEGURANÇA FINANCEIRA
-- =================================================================

-- 1. Criação da Tabela de Logs de Auditoria
CREATE TABLE Log_Auditoria (
    id_log          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome_tabela     VARCHAR2(50)  NOT NULL,
    acao_realizada  VARCHAR2(20)  NOT NULL,
    usuario_banco   VARCHAR2(50)  NOT NULL,
    data_hora       TIMESTAMP     NOT NULL,
    
    CONSTRAINT pk_log_auditoria PRIMARY KEY(id_log)
);


CREATE OR REPLACE TRIGGER trg_audit_contratos
AFTER INSERT OR UPDATE OR DELETE ON Contrato
DECLARE
    v_acao VARCHAR2(20);
BEGIN
    v_acao := CASE
        WHEN INSERTING THEN 'INSERÇÃO'
        WHEN UPDATING  THEN 'ATUALIZAÇÃO'
        WHEN DELETING  THEN 'EXCLUSÃO'
        ELSE 'DESCONHECIDO'
    END;

    -- Insere o registro na tabela de auditoria capturando o usuário logado no SO/Banco
    INSERT INTO Log_Auditoria (nome_tabela, acao_realizada, usuario_banco, data_hora)
    VALUES ('Contrato', v_acao, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSTIMESTAMP);

END;
/

-- =================================================================
-- Visão para os auditores verem rapidamente as equipes com contratos milionários
-- =================================================================
CREATE OR REPLACE VIEW vw_auditoria_financeira AS
SELECT 
    e.nome_equipe, 
    COUNT(c.LEI_patrocinador) AS qtd_patrocinadores,
    NVL(SUM(c.valor), 0)      AS valor_total_arrecadado
FROM Equipe e
LEFT JOIN Contrato c ON e.nome_equipe = c.nome_equipe_patrocinada
GROUP BY e.nome_equipe
HAVING SUM(c.valor) > 100000000; -- Filtra apenas equipes que arrecadaram mais de 100 Milhões


-- =================================================================
-- Simula entrega de permissões no banco de dados
-- =================================================================
-- Permite que qualquer usuário do banco leia a view financeira
GRANT SELECT ON vw_auditoria_financeira TO PUBLIC;

-- Proíbe veementemente que qualquer usuário comum delete os logs de auditoria
REVOKE DELETE ON Log_Auditoria FROM PUBLIC;


-- =================================================================
-- Script para ler os últimos logs de forma procedural
-- =================================================================
DECLARE
    CURSOR c_logs IS 
        SELECT acao_realizada, data_hora 
        FROM Log_Auditoria 
        ORDER BY id_log DESC;
        
    v_acao Log_Auditoria.acao_realizada%TYPE;
    v_data Log_Auditoria.data_hora%TYPE;
    
    v_contador NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- LENDO OS 5 ÚLTIMOS LOGS DE AUDITORIA ---');
    
    OPEN c_logs;
    
    WHILE v_contador < 5 LOOP
        FETCH c_logs INTO v_acao, v_data;
        
        EXIT WHEN c_logs%NOTFOUND; 
        
        DBMS_OUTPUT.PUT_LINE('Ação: ' || v_acao || ' | Data: ' || TO_CHAR(v_data, 'DD/MM/YYYY HH24:MI:SS'));
        
        v_contador := v_contador + 1;
    END LOOP;
    
    CLOSE c_logs;
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------');
END;
/